### ISSUE TITLE
Milestone 0 / Due (Fri 12.13) 5pm

### ISSUE THREAD

**Issue by alexahanthony** [ajrsabet/Screen_Time_Tracker#12]
- [x] assign granular tasks to team members 

- [x] update kanban board

- [x] prep for manatee tank
