### ISSUE TITLE
Milestone 1  MVP / Due (Sun 12.15) 11:59pm

### ISSUE THREAD

**Issue by alexahanthony** [ajrsabet/Screen_Time_Tracker#13]
--basic functionality working--

--art design--

- [x]  basic Home page
(empty div for kid buttons)(Aidan)
- [x]  basic Stats page
(empty div for 2 charts)(Aidan)
- [x]  basic Kid page
(empty div for the youtube)(Alexa)
- [x]  basic styling page
(Alexa)
--Test--
- [x] push to master and test

--back end--

- [x] youtube api
(Liam)
- [x] chart api
(Liam, Adam)
- [x] background image api
(Liam, Adam)
- [x] timer to work
(Liam, Adam)
- [x] local storage
(Adam)
