### ISSUE TITLE
Milestone 2 MDP/ Due (Tue 12.17) 12pm

### ISSUE THREAD

**Issue by alexahanthony** [ajrsabet/Screen_Time_Tracker#14]
--MDP--

front end

- [ ] contact page
- [ ] plus add kids button on home page
- [x] custom style buttons with colors

- [x]  all main styling finished for all pages

back end
- [ ] youtube search works
- [ ] chart to be dynamic
